export interface CurrencyChange {
  name: string; // BTC_LSK
  price: number; // 0.00068002, e.g. 1 LSK to 1 BTC ratio1
  change: number; // -0.03242697 percent of price change over the last 24h
}

export enum Currency {
  amp = 'amp',
  ardr = 'ardr',
  bch = 'bch',
  bcn = 'bcn',
  bcy = 'bcy',
  bela = 'bela',
  blk = 'blk',
  btcd = 'btcd',
  btm = 'btm',
  bts = 'bts',
  burst = 'burst',
  clam = 'clam',
  cvc = 'cvc',
  dash = 'dash',
  dcr = 'dcr',
  dgb = 'dgb',
  doge = 'doge',
  emc2 = 'emc2',
  etc = 'etc',
  eth = 'eth',
  exp = 'exp',
  fct = 'fct',
  fldc = 'fldc',
  flo = 'flo',
  game = 'game',
  gas = 'gas',
  gno = 'gno',
  gnt = 'gnt',
  grc = 'grc',
  huc = 'huc',
  lbc = 'lbc',
  lsk = 'lsk',
  ltc = 'ltc',
  maid = 'maid',
  nav = 'nav',
  neos = 'neos',
  nmc = 'nmc',
  nxc = 'nxc',
  nxt = 'nxt',
  omg = 'omg',
  omni = 'omni',
  pasc = 'pasc',
  pink = 'pink',
  pot = 'pot',
  ppc = 'ppc',
  rads = 'rads',
  rep = 'rep',
  ric = 'ric',
  sbd = 'sbd',
  sc = 'sc',
  steem = 'steem',
  storj = 'storj',
  str = 'str',
  strat = 'strat',
  sys = 'sys',
  via = 'via',
  vrc = 'vrc',
  vtc = 'vtc',
  xbc = 'xbc',
  xcp = 'xcp',
  xem = 'xem',
  xmr = 'xmr',
  xpm = 'xpm',
  xrp = 'xrp',
  xvc = 'xvc',
  zec = 'zec',
  zrx = 'zrx',
}